# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('file', models.FileField(upload_to=b'uploads/audiofiles/')),
                ('length_seconds', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(null=True)),
                ('format', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=b'uploads/stations/')),
                ('subscription_count', models.PositiveIntegerField(default=0)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=2000)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to=b'uploads/tracks/')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.AudioFile')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.Station')),
            ],
        ),
    ]
